# Generated by Django 5.1.2 on 2024-11-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=50)),
                ('diagnostico', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('edad', models.IntegerField()),
                ('alergia', models.CharField(max_length=255)),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('medicamento', models.CharField(max_length=255)),
                ('forma', models.CharField(max_length=255)),
                ('dosis', models.CharField(max_length=255)),
                ('via', models.CharField(max_length=255)),
                ('duracion', models.CharField(max_length=255)),
                ('frecuencia', models.CharField(max_length=255)),
                ('indicaciones', models.CharField(max_length=255)),
            ],
        ),
    ]
