# Generated by Django 5.1.3 on 2024-11-18 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='act_causante',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='act_fisica',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='alimentacion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='condicion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='descanso',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='descripcion_dolor',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='frecuencia_dolor',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='intensidad_dolor',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='lesiones',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicacion_actual',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='presion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='rango_mov',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tratamiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tratamientos_previos',
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receta',
            name='alergia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.paciente'),
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('cardiopatia', models.BooleanField(default=False)),
                ('alergias', models.CharField(blank=True, max_length=50, null=True)),
                ('enfermedad_renal', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('fracturas', models.CharField(blank=True, max_length=50, null=True)),
                ('cirugias', models.CharField(blank=True, max_length=50, null=True)),
                ('lesiones', models.CharField(blank=True, max_length=50, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='EstiloVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=50)),
                ('alimentacion', models.CharField(max_length=50)),
                ('act_fisica', models.CharField(max_length=50)),
                ('alcohol', models.BooleanField(default=False)),
                ('cigarrillo', models.BooleanField(default=False)),
                ('farmacos', models.BooleanField(default=False)),
                ('especifique', models.CharField(blank=True, max_length=50, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ExploracionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=50)),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('talla', models.IntegerField()),
                ('imc', models.IntegerField()),
                ('presion', models.CharField(max_length=50)),
                ('embarazo', models.BooleanField(default=False)),
                ('trimestre', models.CharField(blank=True, max_length=50, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.paciente')),
            ],
        ),
    ]
