# Generated by Django 5.1.3 on 2024-11-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='cuello_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='cuello_i',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='m_inf_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='m_inf_i',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='m_sup_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='m_sup_i',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='torso_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='torso_i',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
