# Generated by Django 5.1.3 on 2024-11-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_historial_cuello_d_alter_historial_cuello_i_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='cuello_dg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='cuello_ig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='m_inf_dg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='m_inf_ig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='m_sup_dg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='m_sup_ig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='torso_dg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='torso_ig',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
