# Generated by Django 5.1.3 on 2024-11-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_historial_cuello_dg_historial_cuello_ig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='abd_mi_cd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='abd_mi_ci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='abd_ms_hd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='abd_ms_hi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='abdr_ms_md',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='abdr_ms_mi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='add_mi_cd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='add_mi_ci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='add_ms_hd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='add_ms_hi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='add_ms_md',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='add_ms_mi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='ext_mi_cd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='ext_mi_ci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='ext_ms_bd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='ext_ms_bi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='ext_ms_md',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='ext_ms_mi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='exth_ms_hd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='exth_ms_hi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='extv_ms_hd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='extv_ms_hi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flex_mi_cd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flex_mi_ci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flex_ms_bd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flex_ms_bi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flex_ms_md',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flex_ms_mi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flexcr_mi_cd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flexcr_mi_ci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flexh_ms_hd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flexh_ms_hi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flexv_ms_hd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flexv_ms_hi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pron_ms_bd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pron_ms_bi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotext_mi_cd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotext_mi_ci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotext_ms_hd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotext_ms_hi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotint_mi_cd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotint_mi_ci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotint_ms_hd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotint_ms_hi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='susp_ms_bd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='susp_ms_bi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
