# Generated by Django 5.1.3 on 2024-11-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_historial_abd_mi_cd_historial_abd_mi_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='dors_mi_pd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='dors_mi_pi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='ever_mi_pd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='ever_mi_pi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='ext_mi_pd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='ext_mi_pi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flex_mi_pd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flex_mi_pi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flexplan_mi_pd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='flexplan_mi_pi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='inve_mi_pd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='inve_mi_pi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotext_mi_pd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotext_mi_pi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotint_mi_pd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='rotint_mi_pi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
