# Generated by Django 5.1.1 on 2024-11-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_loginuserform_registeruserform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruserform',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='registeruserform',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registeruserform',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
