# Generated by Django 5.1.1 on 2024-11-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_registeruserform_cedula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruserform',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='registeruserform',
            name='password2',
        ),
    ]
