# Generated by Django 5.1.1 on 2024-11-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_password1_registeruserform_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruserform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registeruserform',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeruserform',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeruserform',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
