# Generated by Django 5.1.3 on 2024-11-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_registeruserform_is_active_registeruserform_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='pres_atax',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pres_ayud',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pres_claudi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pres_dif',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pres_espa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
