# Generated by Django 5.1.2 on 2024-11-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='horanconsulta',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
